### ISSUE TITLE
运行时卡死，进度一直为0

### ISSUE THREAD

**Issue by lionk007** [FanQinFred/OCRmyPDF-Desktop#2]

**Comment by FanQinFred** [comment]
请提交一下PDF文档，方便复现。感谢！

**Comment by lionk007** [comment]
您的邮件大小超出收件人所在服务商的限制，对方不予接收。


请再提供一个邮箱，然后我发给你

**Comment by FanQinFred** [comment]
> 您的邮件大小超出收件人所在服务商的限制，对方不予接收。
> 
> 请再提供一个邮箱，然后我发给你

caj2pdf@163.com
fanqin@bit.edu.cn
1836459118@qq.com
以上邮箱均可。

**Comment by lionk007** [comment]
已发qq邮箱

**Comment by FanQinFred** [comment]
我这边能正常识别

**Comment by lionk007** [comment]
是不是运行环境的问题？我这边添加完文件就是0，一直旋转。而且cpu那边设置多了后，再过去还是1




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月19日(星期一) 下午3:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FanQinFred/OCRmyPDF-Desktop] 运行时卡死，进度一直为0 (Issue #2)





 
我这边能正常识别

**Comment by dijkstra-mose** [comment]
同样的问题，一直0%

**Comment by sjhsbhqf** [comment]
这个问题，其实是因为win系统最新版本更改了文件夹的权限。你们需要以管理员身份打开软件，不然无法写磁盘

**Comment by sjhsbhqf** [comment]
另一个方面，我发现这个软件是直接覆盖原有PDF，那么这样如果你的PDF正在阅览，可能也会导致无法有效OCR成功

**Comment by sjhsbhqf** [comment]
我用WPS PDF编辑功能的时候，没有发现文字层，不知道作者能不能做出来类似ABBYY FineReader OCR的那种效果，存在一个文字层。

**Comment by FanQinFred** [comment]
各位莫慌 这些问题我都会在圣诞节前全部解决。

**Comment by FanQinFred** [comment]
各位莫慌 这些问题我都会在圣诞节前全部解决。
